const $=s=>document.querySelector(s);
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.error||"Something went wrong");return d}
function openModal(type,extra={}){const m=$("#modal");m.style.display="flex";$("#modalBody").innerHTML=type==="login"?loginForm():registerForm();if(extra.plan) $("#modalBody").dataset.plan=extra.plan}
function closeModal(){$("#modal").style.display="none"}
function loginForm(){return `<h2>Welcome back</h2><p class="muted">Login with your email or mobile number.</p><form onsubmit="login(event)"><div class="field"><label>Email / Mobile</label><input name="login" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="primary form-btn">Login</button></form><div class="msg">New student? <button onclick="openModal('register')">Create account</button></div>`}
function registerForm(){return `<h2>Create your account</h2><p class="muted">Your email will be verified by OTP.</p><form onsubmit="register(event)"><div class="field"><label>Full Name</label><input name="name" required></div><div class="field"><label>Mobile</label><input name="mobile" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Class</label><select name="class_name"><option>Class 1</option><option>Class 2</option><option>Class 3</option><option>Class 4</option><option>Class 5</option><option>Class 6</option><option>Class 7</option><option>Class 8</option><option>Class 9</option><option>Class 10</option><option>Class 11</option><option>Class 12</option></select></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" required></div><button class="primary form-btn">Sign Up</button></form>`}
async function register(e){e.preventDefault();const fd=new FormData(e.target);const d=await api("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});$("#modalBody").innerHTML=`<h2>Verify Email</h2><p>Enter the 6-digit OTP sent to your Gmail.</p><form onsubmit="verifyOtp(event,${d.user_id})"><div class="field"><input name="otp" maxlength="6" placeholder="6-digit OTP" required></div><button class="primary form-btn">Verify OTP</button></form>${d.demo_otp?`<div class="msg">Development OTP: <b>${d.demo_otp}</b></div>`:""}`}
async function verifyOtp(e,id){e.preventDefault();const otp=new FormData(e.target).get("otp");const d=await api("/api/verify-otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:id,otp})});alert(d.message);openModal("login")}
async function login(e){e.preventDefault();try{const fd=new FormData(e.target);const d=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});closeModal();location.href="/dashboard.html"}catch(err){alert(err.message)}}
async function load(){const plans=await api("/api/plans");$("#plans").innerHTML=plans.map((p,i)=>`<div class="plan ${i===2?"recommended":""}"><span class="tag">${i===2?"MOST POPULAR":p.name.toUpperCase()}</span><h3>${p.name}</h3><div class="price">Rs. ${p.price.toLocaleString()}</div><ul>${p.features.split(", ").map(x=>`<li>${x}</li>`).join("")}</ul><button class="primary" onclick="selectPlan(${p.id})">Choose ${p.name}</button></div>`).join("");
const c=await api("/api/courses");$("#courseGrid").innerHTML=c.length?c.map(x=>`<div class="card"><span class="tag">${x.class_name||"All Classes"}</span><h3>${x.title}</h3><p>${x.subject||""}</p><p>${x.description||"Premium recorded lessons and study materials."}</p></div>`).join(""):`<div class="card"><h3>Courses are coming soon</h3><p>Admin can add courses from the management panel.</p></div>`;
const l=await api("/api/live");$("#liveGrid").innerHTML=l.length?l.map(x=>`<div class="card"><span class="tag">${x.class_name}</span><h3>${x.title}</h3><p>${x.subject} · ${x.date} · ${x.start_time}</p><a class="primary" style="display:inline-block;text-decoration:none" href="${x.meeting_link}" target="_blank">Join Live Class</a></div>`).join(""):`<div class="card"><h3>No live classes scheduled</h3><p>Upcoming classes will appear here.</p></div>`}
async function selectPlan(id){try{const me=await api("/api/me");if(!me.user){openModal("login");return}location.href="/dashboard.html?plan="+id}catch(e){openModal("login")}}
load();
